/**
 * 拟定mutation的事件类型（类似于一个抽象接口 abstract interface）
 */

const SET_SINGER = 'SET_SINGER'
const SET_PLAYING = 'SET_PLAYING'
const SET_FULLSCREEN = 'SET_FULLSCREEN'
const SET_MODE = 'SET_MODE'
const SET_SONGLIST = 'SET_SONGLIST'
const SET_SEQUENCELIST = 'SET_SEQUENCELIST'
const SET_CURRENTINDEX = 'SET_CURRENTINDEX'
const SET_RANK = 'SET_RANK'
const SET_ISSHOWLIST = 'SET_ISSHOWLIST'
const SET_USERINFO = 'SET_USERINFO'
const SET_SHOWLOGIN = 'SET_SHOWLOGIN'
const SET_TO = 'SET_TO'
const SET_FROM = 'SET_FROM'

export {
	SET_SINGER,
	SET_PLAYING,
	SET_FULLSCREEN,
	SET_MODE,
	SET_SONGLIST,
	SET_SEQUENCELIST,
	SET_CURRENTINDEX,
	SET_RANK,
	SET_ISSHOWLIST,
	SET_USERINFO,
	SET_SHOWLOGIN,
	SET_TO,
	SET_FROM,
}
