/**
 * 拟定mutation的事件类型（类似于一个抽象接口 abstract interface）
 */

export default {
	SET_SINGER: 'SET_SINGER',
	SET_CURRENT: 'SET_CURRENT',
	SET_PLAYING: 'SET_PLAYING',
	SET_FULLSCREEN: 'SET_FULLSCREEN',
	SET_MODE: 'SET_MODE',
	SET_SONGLIST: 'SET_SONGLIST',
	SET_SEQUENCELIST: 'SET_SEQUENCELIST',
	SET_CURRENTINDEX: 'SET_CURRENTINDEX',
	SET_RANK: 'SET_RANK',
	SET_ISSHOWLIST: 'SET_ISSHOWLIST',
	SET_LOGIN: 'SET_LOGIN',
}
